# Generated by Django 3.0.5 on 2020-04-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_message_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to',
        ),
        migrations.AddField(
            model_name='message',
            name='contact_id',
            field=models.IntegerField(null=True),
        ),
    ]
