# Generated by Django 3.0.5 on 2020-04-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200408_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sms_time',
            field=models.DateTimeField(null=True),
        ),
    ]
